WebApplication3/Controllers/SecretaryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using System.Web.Security;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;

namespace WebApplication3.Controllers
{
    public class SecretaryController : Controller
    {
        private SecDB1 db = new SecDB1();

        // GET: Secretary
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View(db.Secs.ToList());
            }
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult Post_Index()
        {
            List<Sec> list1 = new List<Sec>();
            string pid = Request["pid"];
            if (pid == "")
            {
                IQueryable<Sec> q = from s in db.Secs  select s;
                foreach (var i in q)
                {
                    list1.Add(i);
                }
                ViewBag.pid = pid;
            }
            else
            {
                IQueryable<Sec> q = from s in db.Secs where s.PatientId == pid select s;
                foreach (var i in q)
                {
                    list1.Add(i);
                }
                ViewBag.pid = pid;
            }

            return View(list1);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult sout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            FormsAuthentication.SignOut();
            Session.Abandon();
            Session["uns"] = "";

            return RedirectToAction("Login", "Login");

        }

        // GET: Secretary/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sec sec = db.Secs.Find(id);
                if (sec == null)
                {
                    return HttpNotFound();
                }
                return View(sec);
            }
        }

        // GET: Secretary/Create
        public ActionResult Create()
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View();
            }
        }

        // POST: Secretary/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PatientId,FirstName,SurName,DOB,Address,Gender,ContactNumber,Appointment,AppointmentTime,NextOfKin,MedicalCard,EthnicOrigin,Religion,GPContactDetails,Occupation,Maritalstatus")] Sec sec)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (ModelState.IsValid)
                {
                    db.Secs.Add(sec);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(sec);
            }
        }

        // GET: Secretary/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sec sec = db.Secs.Find(id);
                if (sec == null)
                {
                    return HttpNotFound();
                }
                return View(sec);
            }
        }

        // POST: Secretary/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PatientId,FirstName,SurName,DOB,Address,Gender,ContactNumber,Appointment,AppointmentTime,NextOfKin,MedicalCard,EthnicOrigin,Religion,GPContactDetails,Occupation,Maritalstatus")] Sec sec)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (ModelState.IsValid)
                {
                    db.Entry(sec).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(sec);
            }
        }

        // GET: Secretary/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Sec sec = db.Secs.Find(id);
                if (sec == null)
                {
                    return HttpNotFound();
                }
                return View(sec);
            }
        }

        // POST: Secretary/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Consultant"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                Sec sec = db.Secs.Find(id);
                db.Secs.Remove(sec);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult signout()
        {
            //AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            FormsAuthentication.SignOut();
            Session.Abandon();
            //Session["uns"] = "";
            return RedirectToAction("Login", "Login");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}

WebApplication3/Views/Secretary/Create.cshtml
@model WebApplication3.Models.Sec

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Create</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role  &ensp;&ensp; @Html.ActionLink("User Accounts", "Index", "Login") &ensp; &ensp; @Html.ActionLink("Logout", "sout")</p>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sec</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appointment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appointment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appointment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppointmentTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppointmentTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextOfKin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NextOfKin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NextOfKin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicalCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicalCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MedicalCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EthnicOrigin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EthnicOrigin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EthnicOrigin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Religion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Religion, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Religion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GPContactDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GPContactDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GPContactDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maritalstatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Maritalstatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Maritalstatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/Secretary/Delete.cshtml
@model WebApplication3.Models.Sec

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role  &ensp;&ensp; @Html.ActionLink("User Accounts", "Index", "Login") &ensp; &ensp; @Html.ActionLink("Logout", "sout")</p>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sec</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appointment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appointment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppointmentTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextOfKin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextOfKin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EthnicOrigin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EthnicOrigin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Religion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Religion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPContactDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPContactDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occupation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maritalstatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maritalstatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication3/Views/Secretary/Details.cshtml
@model WebApplication3.Models.Sec

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Details</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role  &ensp;&ensp; @Html.ActionLink("User Accounts", "Index", "Login") &ensp; &ensp; @Html.ActionLink("Logout", "sout")</p>

<div>
    <h4>Sec</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appointment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appointment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppointmentTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextOfKin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextOfKin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EthnicOrigin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EthnicOrigin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Religion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Religion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPContactDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPContactDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occupation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maritalstatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maritalstatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication3/Views/Secretary/Index.cshtml
@model IEnumerable<WebApplication3.Models.Sec>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Secretary - Patient Details</h2>
   <p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role  &ensp;&ensp; @Html.ActionLink("User Accounts", "Index","Login") &ensp; &ensp; @Html.ActionLink("Logout", "sout")</p>

@using (Html.BeginForm("Index", "Secretary"))
{
    <p style=" color:forestgreen">
        @Html.Label("Id")
        <input type="text" name="pid" value="@ViewBag.pid" />
        &ensp; <input type="submit" style="color:midnightblue" value="Search" />
    </p>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SurName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Appointment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppointmentTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NextOfKin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalCard)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EthnicOrigin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Religion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GPContactDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Occupation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Maritalstatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PatientId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SurName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Appointment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppointmentTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NextOfKin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MedicalCard)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EthnicOrigin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Religion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GPContactDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Occupation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Maritalstatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApplication3/Views/Secretary/sout.cshtml
@{
    ViewBag.Title = "sout";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>sout</h2>

 Welcome : @ViewBag.user