WebApplication3/Controllers/NurseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using System.Data.SqlClient;
using System.Web.Security;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;

namespace WebApplication3.Controllers
{
    public class NurseController : Controller
    {
        private NurseDB db = new NurseDB();

        // GET: Nurse
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View(db.Nurses.ToList());
            }
        }
        [HttpPost]
        [ActionName("Index")]
        public ActionResult Post_Index()
        {
            List<Nurse> list1 = new List<Nurse>();
            string pid = Request["pid"];
            if (pid == "")
            {
                IQueryable<Nurse> q = from s in db.Nurses select s;
                foreach (var i in q)
                {
                    list1.Add(i);
                }
                ViewBag.pid = pid;
            }
            else
            {
                IQueryable<Nurse> q = from s in db.Nurses where s.PatientId == pid select s;
                foreach (var i in q)
                {
                    list1.Add(i);
                }
                ViewBag.pid = pid;
            }

            return View(list1);
        }
        public ActionResult sout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            FormsAuthentication.SignOut();
            Session.Abandon();
            Session["uns"] = "";

            return RedirectToAction("Login", "Login");

        }
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        // GET: Nurse/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Nurse nurse = db.Nurses.Find(id);
                if (nurse == null)
                {
                    return HttpNotFound();
                }
                return View(nurse);
            }
        }

        // GET: Nurse/Create
        public ActionResult Create()
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View();
            }
        }

        // POST: Nurse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PatientId,FirstName,PastMedicalHistory,FamilyHistory,MentalStatusExamination,CollateralHistory,NursingCarePlan,AlergicSpecificMedication")] Nurse nurse)
        {
            if (ModelState.IsValid)
            {
                db.Nurses.Add(nurse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nurse);
        }

        // GET: Nurse/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Nurse nurse = db.Nurses.Find(id);
                if (nurse == null)
                {
                    return HttpNotFound();
                }
                return View(nurse);
            }
        }

        // POST: Nurse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PatientId,FirstName,PastMedicalHistory,FamilyHistory,MentalStatusExamination,CollateralHistory,NursingCarePlan,AlergicSpecificMedication")] Nurse nurse)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (ModelState.IsValid)
                {
                    db.Entry(nurse).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(nurse);
            }
        }

        // GET: Nurse/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.user = Session["uns"];
            ViewBag.role = Session["rol"];
            if ((Session["uns"] == null) || (Session["rol"].ToString() == "Secretary"))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Nurse nurse = db.Nurses.Find(id);
                if (nurse == null)
                {
                    return HttpNotFound();
                }
                return View(nurse);
            }
        }

        // POST: Nurse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Nurse nurse = db.Nurses.Find(id);
            db.Nurses.Remove(nurse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Views/Nurse/Create.cshtml
@model WebApplication3.Models.Nurse

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Create</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role &ensp;&ensp; @Html.ActionLink("Secretary Records", "Index", "Secretary") &ensp; &ensp; @Html.ActionLink("Logout", "sout") </p>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nurse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PastMedicalHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PastMedicalHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PastMedicalHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FamilyHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FamilyHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FamilyHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MentalStatusExamination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MentalStatusExamination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MentalStatusExamination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollateralHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollateralHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollateralHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NursingCarePlan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NursingCarePlan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NursingCarePlan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlergicSpecificMedication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlergicSpecificMedication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlergicSpecificMedication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/Nurse/Delete.cshtml
@model WebApplication3.Models.Nurse

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role &ensp;&ensp; @Html.ActionLink("Secretary Records", "Index", "Secretary") &ensp; &ensp; @Html.ActionLink("Logout", "sout") </p>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nurse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PastMedicalHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PastMedicalHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FamilyHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FamilyHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MentalStatusExamination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MentalStatusExamination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollateralHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollateralHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NursingCarePlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NursingCarePlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlergicSpecificMedication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlergicSpecificMedication)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication3/Views/Nurse/Details.cshtml
@model WebApplication3.Models.Nurse

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Details</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role &ensp;&ensp; @Html.ActionLink("Secretary Records", "Index", "Secretary") &ensp; &ensp; @Html.ActionLink("Logout", "sout") </p>
<div>
    <h4>Nurse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PastMedicalHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PastMedicalHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FamilyHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FamilyHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MentalStatusExamination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MentalStatusExamination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollateralHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollateralHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NursingCarePlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NursingCarePlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlergicSpecificMedication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlergicSpecificMedication)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication3/Views/Nurse/Edit.cshtml
@model WebApplication3.Models.Nurse

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role &ensp;&ensp; @Html.ActionLink("Secretary Records", "Index", "Secretary") &ensp; &ensp; @Html.ActionLink("Logout", "sout") </p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nurse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PastMedicalHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PastMedicalHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PastMedicalHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FamilyHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FamilyHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FamilyHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MentalStatusExamination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MentalStatusExamination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MentalStatusExamination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollateralHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollateralHistory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollateralHistory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NursingCarePlan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NursingCarePlan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NursingCarePlan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlergicSpecificMedication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlergicSpecificMedication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlergicSpecificMedication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/Nurse/Index.cshtml
@model IEnumerable<WebApplication3.Models.Nurse>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Nurse Page - Patient Details</h2>
<p style=" color:darkblue"> Welcome : @ViewBag.user  &ensp; Role: @ViewBag.role &ensp;&ensp; @Html.ActionLink("Secretary Records", "Index", "Secretary") &ensp; &ensp; @Html.ActionLink("Logout", "sout") </p>
@using (Html.BeginForm("Index", "Nurse"))
{
    <p style=" color:forestgreen">
        @Html.Label("Id")
        <input type="text" name="pid" value="@ViewBag.pid" />
        &ensp; <input type="submit" style="color:midnightblue" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PastMedicalHistory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FamilyHistory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MentalStatusExamination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CollateralHistory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NursingCarePlan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlergicSpecificMedication)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PatientId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PastMedicalHistory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FamilyHistory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MentalStatusExamination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CollateralHistory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NursingCarePlan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlergicSpecificMedication)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>